### ISSUE TITLE
Deprecation warning on node 6

### ISSUE THREAD

**Issue by hoegertn** [nbu/node-menu#10]
On node 6 the following warning is printed:

` (node:37503) DeprecationWarning: util.print is deprecated. Use console.log instead.`

It is caused by line 186 in `lib/nodemenu.js` which is `util.print(self.CLEAR_CODE);`

**Comment by hoegertn** [comment]
@nbu any ETA for this problem?

**Comment by nbu** [comment]
Hi @hoegertn. Going to fix this problem beginning of the next month.

**Comment by nbu** [comment]
Fixed in 1.0.1

**Comment by hoegertn** [comment]
Perfect thanks. Is it published to npm?

**Comment by nbu** [comment]
@hoegertn, it's published now.
