### ISSUE TITLE
Suggestion make the note under the menu optional/configurable.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [nbu/node-menu#5]
"Please provide input at prompt as: >> ItemNumber arg1 arg2 ... (i.e. >> 2 "string with spaces" 2 4 noSpacesString true)"

It might be desirable for people who use this module to type their own string there to show.

**Comment by nbu** [comment]
Hello Liam. This is good point. Thanks for bringing this up.

**Comment by nbu** [comment]
@mstiles92 Thanks a lot for providing custom prompt support.
